"""Update Agent model with new access levels

Revision ID: 295a7da85e83
Revises: b7069b78670a
Create Date: 2024-07-21 09:31:46.259392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '295a7da85e83'
down_revision = 'b7069b78670a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_link', sa.String(length=64), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('agent_sharing_link_key', type_='unique')
        batch_op.create_unique_constraint(None, ['secret_link'])
        batch_op.drop_column('sharing_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sharing_link', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('agent_sharing_link_key', ['sharing_link'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('secret_link')

    # ### end Alembic commands ###
