"""Add access control to Agent model

Revision ID: b2abbe79cc41
Revises: 
Create Date: 2024-07-19 20:07:09.847327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2abbe79cc41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', sa.Enum('PUBLIC', 'PRIVATE', 'FACULTY', 'CREATOR', name='accesslevel'), nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['access_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('access_token')
        batch_op.drop_column('access_level')

    # ### end Alembic commands ###
