"""Add sharing_link to Agent model

Revision ID: b7069b78670a
Revises: effec35d4d86
Create Date: 2024-07-20 14:04:49.410644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7069b78670a'
down_revision = 'effec35d4d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sharing_link', sa.String(length=64), nullable=True))
        batch_op.drop_constraint('agent_share_token_key', type_='unique')
        batch_op.create_unique_constraint(None, ['sharing_link'])
        batch_op.drop_column('is_public')
        batch_op.drop_column('share_token')
        batch_op.drop_column('is_shared')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('share_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('agent_share_token_key', ['share_token'])
        batch_op.drop_column('sharing_link')

    # ### end Alembic commands ###
