"""Add share_token and is_shared to Agent model

Revision ID: effec35d4d86
Revises: b2abbe79cc41
Create Date: 2024-07-20 13:25:10.849936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effec35d4d86'
down_revision = 'b2abbe79cc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('agent_access_token_key', type_='unique')
        batch_op.create_unique_constraint(None, ['share_token'])
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('agent_access_token_key', ['access_token'])
        batch_op.drop_column('is_shared')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
